
palavras_chaves = {
    "carro morrendo": "carro morrendo sozinho",
    "carro falhando": "motor falhando",
    "filtro de combustível": "filtro de combustível",
    "água do radiador": "radiador",
    "freio baixo": "freio baixo",
    "óleo baixo": "nível de óleo",
    "luz da injeção acesa": "luz da injeção acesa",
    "barulho ao frear": "pastilhas ou discos",
    "superaquecimento": "radiador ou bomba d'água",
    "motor falhando": "velas ou injetores",
    "bateria fraca": "bateria",
    "pneus desgastados": "pneus",
    "farol apagado": "farol",
    "água do radiador baixa": "radiador",
    "óleo sujo": "óleo",
    "filtro de ar sujo": "filtro de ar",
    "carro puxando para um lado": "alinhamento ou suspensão",
    "vazamento de óleo": "vazamento de óleo",
    "luz do freio acesa": "luz do freio acesa",
    "luz do airbag acesa": "luz do airbag acesa",
    "luz do abs acesa": "luz do abs acesa",
    "carro não liga": "carro não liga",
    "barulho no motor": "barulho no motor",
    "vibração ao dirigir": "vibração ao dirigir",
    "cheiro de queimado": "cheiro de queimado",
    "luz do óleo acesa": "luz do óleo acesa",
    "luz do alternador acesa": "luz do alternador acesa",
    "luz do combustível acesa": "luz do combustível acesa",
    "luz do motor acesa": "luz do motor acesa",
    "luz do sistema de tração acesa": "luz do sistema de tração acesa",
    "luz do sistema de estabilidade acesa": "luz do sistema de estabilidade acesa",
    "luz do sistema de controle de cruzeiro acesa": "luz do sistema de controle de cruzeiro acesa",
    "luz do sistema de monitoramento de pressão dos pneus acesa": "luz do sistema de monitoramento de pressão dos pneus acesa",
    "luz do sistema de assistência de partida em rampa acesa": "luz do sistema de assistência de partida em rampa acesa",
    "luz do sistema de frenagem de emergência acesa": "luz do sistema de frenagem de emergência acesa",
    "luz do sistema de reconhecimento de sinais de trânsito acesa": "luz do sistema de reconhecimento de sinais de trânsito acesa",
    "luz do sistema de visão noturna acesa": "luz do sistema de visão noturna acesa",
    "luz do sistema de assistência de faixa acesa": "luz do sistema de assistência de faixa acesa",
    "luz do sistema de estacionamento acesa": "luz do sistema de estacionamento acesa",
    "luz do sistema de câmera de ré acesa": "luz do sistema de câmera de ré acesa",
    "luz do sistema de controle de estabilidade acesa": "luz do sistema de controle de estabilidade acesa",
    "luz do sistema de controle de tração acesa": "luz do sistema de controle de tração acesa",
    "luz do sistema de controle de cruzeiro adaptativo acesa": "luz do sistema de controle de cruzeiro adaptativo acesa",
    "luz do sistema de assistência de ponto cego acesa": "luz do sistema de assistência de ponto cego acesa",
    "luz do sistema de assistência de colisão acesa": "luz do sistema de assistência de colisão acesa",
    "luz do sistema de assistência de manutenção de faixa acesa": "luz do sistema de assistência de manutenção de faixa acesa",
    "luz do sistema de assistência de estacionamento acesa": "luz do sistema de assistência de estacionamento acesa",
    "luz do sistema de assistência de frenagem acesa": "luz do sistema de assistência de frenagem acesa",
    "luz do sistema de assistência de partida em rampa acesa": "luz do sistema de assistência de partida em rampa acesa",
    "luz do sistema de assistência de visão noturna acesa": "luz do sistema de assistência de visão noturna acesa",
    "luz do sistema de assistência de reconhecimento de sinais de trânsito acesa": "luz do sistema de assistência de reconhecimento de sinais de trânsito acesa",
    "luz do sistema de assistência de controle de cruzeiro acesa": "luz do sistema de assistência de controle de cruzeiro acesa",
    "luz do sistema de assistência de controle de tração acesa": "luz do sistema de assistência de controle de tração acesa",
    "luz do sistema de assistência de controle de estabilidade acesa": "luz do sistema de assistência de controle de estabilidade acesa",
    "luz do sistema de assistência de ponto cego acesa": "luz do sistema de assistência de ponto cego acesa",
    "luz do sistema de assistência de colisão acesa": "luz do sistema de assistência de colisão acesa",
    "luz do sistema de assistência de manutenção de faixa acesa": "luz do sistema de assistência de manutenção de faixa acesa",
    "luz do sistema de assistência de estacionamento acesa": "luz do sistema de assistência de estacionamento acesa",
    "luz do sistema de assistência de frenagem acesa": "luz do sistema de assistência de frenagem acesa",
    "luz do sistema de assistência de partida em rampa acesa": "luz do sistema de assistência de partida em rampa acesa",
}
